gun1=int(input("1. gün okudunuz sayfa sayısını giriniz "))
gun2=int(input("2. gün okudunuz sayfa sayısını giriniz "))
gun3=int(input("3. gün okudunuz sayfa sayısını giriniz "))
gun4=int(input("4. gün okudunuz sayfa sayısını giriniz "))
gun5=int(input("5. gün okudunuz sayfa sayısını giriniz "))
gun6=int(input("6. gün okudunuz sayfa sayısını giriniz "))
gun7=int(input("7. gün okudunuz sayfa sayısını giriniz "))
toplam=(gun1+gun2+gun3+gun4+gun5+gun6+gun7)
print("Okudunuz sayfa sayısı :",toplam)